cairo-book/cairo-book

src/SUMMARY.md
src/ch00-01-foreword.md
src/ch_00-00-introduction.md

feat: foreword

---

src/SUMMARY.md
src/appendix-00.md
src/appendix-04-useful-development-tools.md
src/ch01-02-hello-world.md

feat:hello-world

---

src/SUMMARY.md
src/ch02-04-comments.md

feat: added ch2 and comments

---

src/SUMMARY.md
src/ch02-00-common-programming-concepts.md
src/ch02-01-variables-and-mutability.md
src/ch02-02-data-types.md
src/chapter_1.md

Closes #13 
2 hours as expected

feat: variables

---

README.md

We need a description on the readme for OnlyDust (asked by OD)

ref: add readme description

---

src/SUMMARY.md
src/ch04-00-using-structs-to-structure-related-data.md
src/ch04-01-defining-and-instantiating-structs.md
src/ch04-02-an-example-program-using-structs.md

Closes #23 
Time spend: 1 hour
Some notes:
- Assessing Ownership of Struct Data with lifetimes feature as TODO as I'm not familiar with Cairo *lifetimes* feature and this related to later chapter
- Code tested
- I presume we'll have chapter 3 for Ownership so I count this as chapter 4, for naming the Listings
- Please correct me if I'm wrong here: **Cairo doesn't have these features for structs**:
- [Creating Instances from Other Instances with Struct Update Syntax](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#creating-instances-from-other-instances-with-struct-update-syntax)
- [Using Tuple Structs Without Named Fields to Create Different Types](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#using-tuple-structs-without-named-fields-to-create-different-types) …

Defining and Instantiating Structs

---

src/SUMMARY.md
src/ch05-00-enums-and-pattern-matching.md
src/ch05-02-the-match-control-flow-construct.md

Closes #27 
Time spent: 2 hours

feat: add match control flow construct page

---

src/ch01-01-installation.md

feat: cairo installation

---

src/ch02-05-control-flow.md

Replace Rust By Cairo

---

src/SUMMARY.md
src/ch03-00-understanding-ownership.md
src/ch03-01-what-is-ownership.md
src/ch03-02-references-and-borrowing.md

Closes #34 
Time spent: 4 hours

feat: ownership

---

src/SUMMARY.md
src/ch04-03-method-syntax.md

Closes #25 
Time spent: 2 hours

feat: method-syntax

---

src/SUMMARY.md
src/ch06-03-paths-for-referring-to-an-item-in-the-module-tree.md

close #46 
I tried to show the path possibilities that I know, if you know more of them feel free to tell me I'll add them :)

feat: add paths explainations

---

src/SUMMARY.md
src/appendix-04-useful-development-tools.md
src/ch00-00-introduction.md
src/ch00-01-foreword.md
src/ch07-00-generic-types.md
src/ch07-02-traits-in-cairo.md
src/title-page.md

Add an intro page, and move some content where it belongs

refactor: content

---

src/SUMMARY.md
src/ch06-01-packages-and-crates.md

This introduces users to crates and closes #44 
It's a short and simple one. I don't think it's worth rewriting a copy of the scarb doc but tell me if you think something would be relevant here.

feat: add what is a crate

---

src/ch02-02-data-types.md

fix: typos

---

src/SUMMARY.md
src/ch06-04-bringing-paths-into-scope-with-the-use-keyword.md

This closes #47 
I wasn't able to complete the `Using external packages (with Scarb)` section. It might be a problem on my side but I couldn't  use the cairo lib with the quaireaux example. I think it might not be ready so in the meantime I added a note.
What do you think?

feat: add use keyword usage

---

src/SUMMARY.md
src/ch02-02-data-types.md
src/ch02-06-common-collections.md

Fix issue #62 
- Add **Common Collections** page (ch02-06)
- Move array from **Data Types** to **Common Collections**
- Add span to **Common Collections**

Add Common Collections page + move array to it and add span

---

src/ch02-02-data-types.md

fix: fix example of tuple

---

src/ch03-01-what-is-ownership.md
src/ch03-02-references-and-snapshots.md
src/ch04-02-an-example-program-using-structs.md
src/ch04-03-method-syntax.md
src/ch05-01-enums.md
src/ch05-02-the-match-control-flow-construct.md

Bundle of misc fixes including grammar, formatting & code.

Fix : Text, grammar & code

---

src/SUMMARY.md
src/ch09-00-error-handling.md
src/ch09-01-error-handling.md

:rocket: feat: add error handling chapter

---

src/ch02-02-data-types.md
src/ch02-05-control-flow.md
src/ch02-06-common-collections.md

Closes #99
Closes #100
Closes #101
Closes #102

fix: content

---

src/ch05-01-enums.md

Adds an Iterative example in the enums section.

added iterative example

---

src/ch05-01-enums.md

fix: enum echo example

---

src/SUMMARY.md
src/appendix-03-derivable-traits.md

feat: Appendix Derivable Traits

---

src/ch09-01-unrecoverable-errors-with-panic.md

feat: nopanic and panic_with

---

src/SUMMARY.md
src/appendix-02-operators-and-symbols.md
src/appendix-04-useful-development-tools.md

feat: Appendix Operators and Symbols

---

po/es.po

I have added new chapters, as well as corrections that have been made, it is very good flow since any changes in `poedit` also indicate these changes to be reviewed.

Update i18n: Spanish Version es.po

---

src/ch99-01-01-introduction-to-smart-contracts.md

Nothing too serious, just typo

fixing a typo

---

book.toml

Adds link to edit (and to the repo)

GitHub and edit links

---

po/es.po
po/messages.pot

Hi team, I have uploaded some comments in the Message.pot, I had to change some settings as some data was not loading, I think it is now all synchronised.
I also added the new appendices structures, and Keyword translations, as well as some other things from the new flow.
I hope everything is ok, I've tested it locally, best regards.

i18n Spanish and Messages.pot

---

README.md

Add all contributors app to the readme

feat: add allcontrib readme

---

src/SUMMARY.md
src/ch10-00-advanced-features.md
src/ch10-01-operator-overloading.md

feat: operator overloading

---

src/appendix-01-keywords.md
src/appendix-05-most-common-types-and-traits.md
src/ch02-02-data-types.md

Fix: Some typos in the appendix and solved 1 todo.

---

po/zh-cn.po

Routine work to maintain the Chinese version.

Update: Add new translations from main branch & Fixed typos

---

po/zh-cn.po

Routine work to make the Chinese version keeps up with the latest English version.

[i18n]Zh cn update0611

---

po/zh-cn.po

Routine work to make the Chinese version keeps up with the latest English versions.

[i18n]Zh cn update0615

---

listings/ch05-enums-and-pattern-matching/no_listing_07_missing_match_arm.cairo
src/ch05-02-the-match-control-flow-construct.md

fix: missing example

---

listings/ch02-common-programming-concepts/no_listing_36_named_parameters.cairo
src/ch02-03-functions.md

feat: named parameters

---

src/ch01-01-installation.md
src/ch01-02-hello-world.md
src/ch01-03-hello-scarb.md

feat: vscode instruction updates

---

listings/ch02-common-programming-concepts/no_listing_36_named_parameters.cairo
listings/ch05-enums-and-pattern-matching/no_listing_07_missing_match_arm.cairo
listings/ch99-starknet-smart-contracts/listing_99_10_assert_balance.cairo
listings/ch99-starknet-smart-contracts/listing_99_11_simple_access_control.cairo
po/zh-cn.po
src/SUMMARY.md
src/ch02-03-functions.md
src/ch05-02-the-match-control-flow-construct.md
src/ch07-02-traits-in-cairo.md
src/ch99-03-security-considerations.md

Simplified trait function definition

---

listings/ch02-common-programming-concepts/no_listing_36_named_parameters.cairo
listings/ch05-enums-and-pattern-matching/no_listing_07_missing_match_arm.cairo
listings/ch99-starknet-smart-contracts/listing_99_10_assert_balance.cairo
listings/ch99-starknet-smart-contracts/listing_99_11_simple_access_control.cairo
po/zh-cn.po
src/SUMMARY.md
src/appendix-02-operators-and-symbols.md
src/appendix-03-derivable-traits.md
src/ch02-03-functions.md
src/ch05-02-the-match-control-flow-construct.md
src/ch99-03-security-considerations.md

Added StorageAccess to appendix 3

---

po/es.po
po/messages.pot

Hi team, here are the translations of all the new changes for Spanish

Update i18n - Spanish

---

po/zh-cn.po

Routine work to maintain the Chinese version.

[i18n]Zh-cn update 0628

---

src/ch15-00-dictionaries.md

As the initial value is zero, it should starts with an initial value of zero or am I missing something? 😅

Update dictionaries initial value in tables

---

src/appendix-02-operators-and-symbols.md

feat: add short circuiting bitwise operators

---

src/ch01-03-hello-scarb.md
src/ch99-00-starknet-smart-contracts.md

feat: scarb config for starknet

---

src/ch99-01-04-01-voting-contract.md

The book read: 
Aside from Scarb you will no have Starkli installed.
Changed to:
Aside from Scarb you will need to have Starkli installed.

Fixed typo 

---

src/ch01-02-hello-world.md

Broken: https://docs.swmansion.com/scarb/docs/starknet/contract-target
New: https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#compiling-external-contracts

Fix broken Scarb link

---

po/zh-cn.po

Merge from main and translate new changes to Chinese.

[i18n]Zh-cn update 0830

---

po/zh-cn.po

optimize the description of integer division
especially 'But when y does not divide x'

optimize the description of integer division

---

src/ch02-99-02-dictionaries.md

refactor: update dict section

---

src/ch01-02-hello-world.md

refactor: scarb cairo-run

---

src/appendix-01-keywords.md

refactor: keywords

---

listings/ch02-99-common-collections/no_listing_03_array_get/src/lib.cairo
listings/ch02-99-common-collections/no_listing_07_intro/src/lib.cairo
listings/ch02-99-common-collections/no_listing_08_intro_rewrite/src/lib.cairo
listings/ch02-99-common-collections/no_listing_09_entries/src/lib.cairo
listings/ch02-99-common-collections/no_listing_10_custom_methods/src/lib.cairo
listings/ch02-99-common-collections/no_listing_11_dict_of_complex/src/lib.cairo
listings/ch02-99-common-collections/no_listing_12_dict_struct_member/src/lib.cairo
listings/ch03-understanding-ownership/no_listing_06_no_destruct_compile_fails/src/lib.cairo
listings/ch03-understanding-ownership/no_listing_07_destruct_compiles/src/lib.cairo
listings/ch05-enums-and-pattern-matching/listing_05_05/src/lib.cairo
listings/ch05-enums-and-pattern-matching/no_listing_01_enum_example/src/lib.cairo
listings/ch05-enums-and-pattern-matching/no_listing_02_enum_message/src/lib.cairo
listings/ch05-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo
listings/ch05-enums-and-pattern-matching/no_listing_07_missing_match_arm/src/lib.cairo
listings/ch07-generic-types-and-traits/no_listing_08_option/src/lib.cairo
listings/ch09-error-handling/listing_01/src/lib.cairo
listings/ch09-error-handling/no_listing_05_panic_with/src/lib.cairo
listings/ch99-starknet-smart-contracts/listing_99_13_storage_packing/src/lib.cairo
src/ch05-01-enums.md

update: cairo 2.2.0

---

po/zh-cn.po

For version 2.20.
Merge from main & Translate new changes to Chinese.

[i18n]zh-cn update0918 

---

src/ch01-01-installation.md

feat: install extension

---

listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_06_05/src/lib.cairo

Hi @enitrat 
Tell me if that's ok for you :)

7.4. scope_precision

---

src/ch99-00-starknet-smart-contracts.md

fix: Scarb link chapter 12

---

src/ch08-02-traits-in-cairo.md

not incorrect but replacing it with more idiomatic approach.

fix: typo fixed

---

listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_06_05/src/lib.cairo
src/ch02-02-data-types.md
src/ch99-01-03-01-storage-variables.md

@enitrat  tell me what you think about these modifications :)
Closes #367

Precisions about Integer/struct/mapping storage

---

src/ch01-02-hello-world.md
src/ch99-00-starknet-smart-contracts.md

refactor: Starknet Scarb support location

---

listings/ch99-starknet-smart-contracts/listing_99_04_L1_L2_messaging/src/lib.cairo
src/ch99-04-00-L1-L2-messaging.md

This PR adds simplicity to the code illustrating how the messaging works + some details on the "how".
Additionally, I've made a complete tutorial with working contracts to work locally with Anvil and Katana.
@enitrat sorry for the delay, I wanted to finish the PR on Katana to support messaging before writing this. :)
I would be very happy to have your feedback on this and from others interested on this topic!

refactor: proposition for new `L1-L2` messaging content

---

src/SUMMARY.md
src/appendix-05-common-types-and-traits-and-cairo-prelude.md
src/appendix-05-most-common-types-and-traits.md

Resolution of #380 
-Small touch-up of appendix E
-Adding a prelude part
Let me know if this is the resume format you want. If not, let me know.
Enjoy the review ;)

Adding information about prelude in Appendix 5

---

src/ch99-01-03-05-optimizing-storage.md

chore: minor fixes to packing

---

book.toml
theme/index.hbs

Add Starkware google analytics to measure basic traffic info (Unique users, visitors, and IPs ==> no cookies).

feat: add g analytics

---

src/appendix-05-common-types-and-traits-and-cairo-prelude.md
src/ch02-05-control-flow.md
src/ch03-01-arrays.md
src/ch03-03-custom-data-structures.md
src/ch07-02-defining-modules-to-control-scope.md
src/ch08-00-generic-types-and-traits.md
src/ch08-01-generic-data-types.md
src/ch08-02-traits-in-cairo.md
src/ch10-01-unrecoverable-errors-with-panic.md
src/ch11-02-macros.md

Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.

fix: several typos in the docs

---

.github/workflows/install-mdbook/action.yml
.github/workflows/mdbook.yml
README.md
book.toml
theme/css/last-changed.css

Feat: Add last change page footer

---

translations/README-cn.md

add README-CN.md

---

translations/README-cn.md

fix README-cn.md img url

---

listings/ch04-understanding-ownership/no_listing_02_pass_array_by_value/src/lib.cairo
src/ch02-01-variables-and-mutability.md
src/ch04-01-what-is-ownership.md
src/ch04-02-references-and-snapshots.md

Addresses #382 
Clarify what the linear type system is for.
Clarify what moving and destroying means.
Clarify the semantics of `Copy`, and specifically introduce a distinction between 'variables' and 'values'.
Clarify the cost of the Copy and desnap operators.
Reorganise a few elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/449)

Rewrite Ch04 - What is Ownership

---

src/ch10-02-recoverable-errors.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/494)

is_err takes a snapshot, not a mutable reference.

---

listings/ch09-testing-cairo-programs/listing_08_09/src/lib.cairo
src/ch10-01-unrecoverable-errors-with-panic.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/493)

double quote  `should_panic` small fix

---

po/es.po

Routine work to maintain the spanish version update,  @omarespejel
- Introduction
- Chapter.01
- Chapter.01.01-Installation
- Chapter.01.02-Hello-World!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/497)

[i18n] Update Es, Introduction, Chapter.01

---

po/es.po

Routine work to maintain the spanish version update, @omarespejel
Chapter.02-Common Programming Concepts
Chapter.02.01-Variables and Mutability
Chapter.02.02-Data Types
Chapter.02.03-Functions
Chapter.02.04-Comments
Chapter.02.05-Control Flow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/499)

[i18n] Update Es, Chapter.02

---

po/es.po

Routine work to maintain the spanish version update, @omarespejel.
Add and Fix translation:
Chapter.03-Common Collections
Chapter.03.01-Arrays
Chapter.03.02-Dictionaries
Chapter.03.03-Custom Data Structures
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/501)

[i18n] Update Es, Chapter.03

---

listings/ch06-enums-and-pattern-matching/no_listing_03_enum_option/src/lib.cairo
listings/ch09-testing-cairo-programs/no_listing_07_integration_test/src/tests/integration_tests.cairo
listings/ch09-testing-cairo-programs/no_listing_09_benchmark_gas/src/lib.cairo
listings/ch99-starknet-smart-contracts/components/listing_03_test_component/src/tests_deployed.cairo
listings/ch99-starknet-smart-contracts/components/listing_03_test_component/src/tests_direct.cairo
listings/ch99-starknet-smart-contracts/listing_99_13_storage_packing/src/lib.cairo
src/ch09-01-how-to-write-tests.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/512)

feat: remove available gas

---

src/appendix-02-operators-and-symbols.md

Closes #435 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/514)

feat: add bitnot(~) and ? operators

---

src/SUMMARY.md
src/ch06-02-the-match-control-flow-construct.md
src/ch11-03-hash.md
src/ch99-04-00-L1-L2-messaging.md

Caught a few minor while reading the doc. Hope I could be of any help :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/518)

chore: a bit of proofreading

---

src/ch99-01-04-01-voting-contract.md

added notes on the versions to be used for the example to work properly, updated all redirection links.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/517)

update: ch99-01-04-01-voting-contract.md

---

src/ch99-01-03-03-contract-events.md

Corrected the minor event typo
Closes https://github.com/cairo-book/cairo-book/issues/507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/519)

fix: minor typo

---

scripts/README.md
scripts/display_build_diff.sh

* feat: listing renaming script
* docs: add script readme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/530)

feat: build diff script (#528)

---

listings/ch02-common-programming-concepts/no_listing_01_variables_are_immutable/src/lib.cairo
listings/ch02-common-programming-concepts/no_listing_02_adding_mut/src/lib.cairo
listings/ch02-common-programming-concepts/no_listing_04_shadowing_different_type/src/lib.cairo
listings/ch02-common-programming-concepts/no_listing_05_mut_cant_change_type/src/lib.cairo
src/ch02-01-variables-and-mutability.md

Resolves #533
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/536)

maintain: Chapter 2-1

---

src/ch03-02-dictionaries.md
src/ch03-03-custom-data-structures.md

Reworded summary of chapters 3.2 and 3.3
Resolves #543
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/545)

Resolves #543

---

book.toml
src/ch01-02-hello-world.md
src/ch02-01-variables-and-mutability.md
src/ch02-02-data-types.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/540)

maintain: Small fix  in chapter 1 and 2 

---

src/ch02-05-control-flow.md

Resolves #550
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/549)

maintain: Chapter-2-5

---

listings/ch04-understanding-ownership/no_listing_09_snapshots/src/lib.cairo
src/ch04-02-references-and-snapshots.md

Resolves #560
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/572)

Maintain Chapter 4-2

---

src/ch00-01-foreword.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/579)

acknowledge rust book

---

listings/ch06-enums-and-pattern-matching/no_listing_06_match_pattern_bind/src/lib.cairo
listings/ch06-enums-and-pattern-matching/no_listing_07_match_option/src/lib.cairo
src/ch06-02-the-match-control-flow-construct.md

Resolves #563
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/575)

Maintain Chapter 6-2

---

src/ch07-00-managing-cairo-projects-with-packages-crates-and-modules.md
src/ch07-01-packages-and-crates.md
src/ch07-02-defining-modules-to-control-scope.md
src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
src/ch07-05-separating-modules-into-different-files.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/582)

fix Chapter 7

---

listings/ch08-generic-types-and-traits/no_listing_14_compiling/src/lib.cairo
listings/ch10-error-handling/no_listing_01_panic/src/lib.cairo
listings/ch10-error-handling/no_listing_09_panic_macro/src/lib.cairo
listings/ch99-starknet-smart-contracts/listing_99_12_vote_contract/src/lib.cairo
src/ch99-01-04-01-voting-contract.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/591)

chore: remove == bool

---

src/title-page.md

Resolves #243
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/595)

feat: reference cairovm.codes playground

---

src/ch01-02-hello-world.md

Add a dash to follow the standard convention from the docs: https://docs.swmansion.com/scarb/docs.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/598)

improve ch01-02-hello-world.html - add a dash for consistency 

---

src/title-page.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/597)

correct StarkWare capitalization

---

src/ch11-03-hash.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/619)

Missing word ch11-03-hash.md

---

src/ch99-01-05-02-component-dependencies.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/625)

chore(component): add precision on `get_dep_component` macro

---

src/ch99-01-05-02-component-dependencies.md

@TAdev0 please TAL
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/627)

chore: improve component dependencies section

---

src/SUMMARY.md

@enitrat  i forgot to annotate empty sections
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/628)

Update summary visibility

---

.github/workflows/mdbook.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/632)

fix: workflow

---

src/ch01-02-hello-world.md

Update link to [Chapter Macros](https://book.cairo-lang.org/ch11-06-macros.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/634)

Update ch01-02 macro.md

---

src/ch02-01-variables-and-mutability.md
src/ch10-01-how-to-write-tests.md
src/ch11-01-custom-data-structures.md
src/ch11-06-macros.md
src/ch13-00-building-starknet-smart-contracts.md
src/ch13-02-contract-functions.md
src/ch15-02-01-under-the-hood.md
src/ch15-02-02-component-dependencies.md
src/ch15-02-03-testing-components.md
src/ch15-02-composability-and-components.md
src/ch16-01-general-recommendations.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/635)

fix: dead links

---

listings/ch11-advanced-features/no_listing_03_hash_trait/src/lib.cairo
src/appendix-03-derivable-traits.md
src/ch11-05-hash.md

Fix some issues mentioned in #568
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/644)

ch11 add serialization explanation and minor additions

---

src/ch06-01-enums.md

https://github.com/starkware-libs/cairo/blob/a14705ac42bfc25e7ec2f87ec1d0c4ec781b5820/corelib/src/option.cairo#L3-L6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/671)

fix option error

---

src/ch01-01-installation.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/669)

feat: add sierra in scarb version

---

src/appendix-07-system-calls.md
src/ch11-06-macros.md
src/ch14-02-contract-dispatchers-library-dispatchers-and-system-calls.md

Closes #643
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/653)

feat: selector! macro

---

src/ch03-02-dictionaries.md

Use of the function `new` of  `NullableTrait` cf. https://community.starknet.io/t/cairo-v2-2-0-is-out/99263
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/676)

fix: Update ch03-02-dictionaries.md

---

listings/ch06-enums-and-pattern-matching/no_listing_12_match_tuple/src/lib.cairo
src/ch06-02-the-match-control-flow-construct.md

#596
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/691)

feat: 2.6.0. underscore pattern tuple

---

src/ch14-01-contract-storage.md

Closes #523
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/694)

feat: 2.5.0 bytearray now implements Store trait

---

src/ch11-07-inlining-in-cairo.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/719)

typos inlining

---

theme/pkg/README.md
theme/pkg/package.json
theme/pkg/wasm-cairo.d.ts
theme/pkg/wasm-cairo.js
theme/pkg/wasm-cairo_bg.wasm.d.ts

As title.
You can find more about WASM-Cairo 0.8.3 [here](https://github.com/cryptonerdcn/wasm-cairo/releases/tag/v0.8.3).
@enitrat Sorry for late! Can you review this update? Thanks!
@TAdev0 @kwkr @Enenche23
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/728)

Update WASM-Cairo to v0.8.3.

---

src/ch01-00-getting-started.md

Closes #725
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/738)

feat: add discord & chatbot links

---

src/ch11-07-inlining-in-cairo.md

Fixing typo Cams to Casm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/740)

Update ch11-07-inlining-in-cairo.md Cams Casm

---

.github/workflows/ci.yml
.github/workflows/install-mdbook/action.yml
.gitignore
book.toml
runner_crate/Scarb.toml

Adds support for https://github.com/cairo-book/mdbook-quiz-cairo, a cairo-specific version of mdbook-quiz with Cairo program validation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/746)

feat: support mdbook-quiz-cairo

---

.github/workflows/mdbook.yml
.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/747)

dev: CI install scarb

---

theme/book.js
theme/js/index.mjs
theme/js/worker.cjs
theme/pkg/README.md
theme/pkg/package.json
theme/pkg/wasm-cairo.d.ts
theme/pkg/wasm-cairo.js
theme/pkg/wasm-cairo_bg.wasm.d.ts

@enitrat @gaetbout 
Add run tests feature to WASM-Cairo to solve these issues:
https://github.com/cairo-book/cairo-book/issues/733
and 
https://github.com/cryptonerdcn/wasm-cairo/issues/18
You can see more about WASM-Cairo 0.8.8&0.8.7 here:
https://github.com/cryptonerdcn/wasm-cairo/releases/tag/v0.8.8
and
https://github.com/cryptonerdcn/wasm-cairo/releases/tag/v0.8.7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/748)

Feature/wasm cairo0.8.8

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/749)

Add instruction to install mdbook-quiz-cairo in the readme

---

quizzes/ch03-01-arrays.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/752)

feat: typo fix in arrays quiz

---

src/SUMMARY.md
src/appendix-000.md

Closes #742
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/756)

fix docs appendix

---

listings/ch05-using-structs-to-structure-related-data/listing_01_user_struct/src/lib.cairo
listings/ch05-using-structs-to-structure-related-data/listing_02_mut_struct/src/lib.cairo
src/ch05-01-defining-and-instantiating-structs.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/762)

fix ByteArray / felt252

---

listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/lib.cairo
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/pizza.cairo
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo
src/ch17-02-testing-smart-contracts.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/767)

fix: foundry tests

---

quizzes/ch06-01-enums.toml
src/ch06-01-enums.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/769)

Add enums quiz

---

quizzes/ch06-02-match.toml
src/ch06-02-the-match-control-flow-construct.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/771)

add match quiz

---

src/ch08-01-generic-data-types.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/773)

fix: fix grammatical error in chapter 8.1

---

quizzes/ch09-02-error-handling-result.toml
src/ch09-02-recoverable-errors.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/775)

add quiz for error handling Result chapter

---

listings/ch06-enums-and-pattern-matching/no_listing_02_enum_with_values_example/src/lib.cairo

Do I count as an airdrop farmer now?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/794)

chore: fix typo

---

src/ch14-02-contract-functions.md

removed the listing as it is not consistent with other snippets and the flow of the chapter
it also contained wrong explanation, that was an error from another PR of mine, my bad
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/796)

fix: error with listing

---

quizzes/ch06-03-concise-control-flow-with-if-let-and-while-let.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/792)

feat: add quiz for ch06-03

---

quizzes/ch07-01-packages-and-crates.toml
quizzes/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/791)

feat: add quizzes for ch07

---

quizzes/ch05-02-an-example-program-using-structs.toml
src/ch05-02-an-example-program-using-structs.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/782)

feat: add quiz questions for example program using structs

---

quizzes/ch04-01-what-is-ownership.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/800)

feat: add quiz ownership 4.1

---

quizzes/ch04-02-references-and-snapshots.toml
src/ch04-02-references-and-snapshots.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/803)

add quiz for references and snapshots

---

listings/ch05-using-structs-to-structure-related-data/listing_01_user_struct/src/lib.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/805)

fix: double quotes for ByteArray

---

src/ch03-02-dictionaries.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/808)

Update ch03-02-dictionaries.md > remove redundant word "complex <ones> types"

---

quizzes/ch03-02-dictionaries.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/809)

Update quizzes/ch03-02-dictionaries.toml > small update to wording and grammar

---

quizzes/ch08-02-traits.toml
src/ch08-02-traits-in-cairo.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/807)

add traits quiz

---

quizzes/ch09-01-unrecoverable-errors-with-panic.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/793)

feat: add quiz for chapter09-01

---

quizzes/ch09-01-unrecoverable-errors-with-panic.toml
src/ch09-01-unrecoverable-errors-with-panic.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/787)

 Unrecoverable errors with panic Chapter 9.1

---

src/ch02-05-control-flow.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/824)

chore: remove duplicate word

---

quizzes/ch05-03-method-syntax.toml
src/ch05-03-method-syntax.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/783)

feat: add quiz for ch05-03

---

src/ch11-01-custom-data-structures.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/837)

Fix Alexandria's data_structures link

---

quizzes/ch11-01-custom-structs.toml
src/ch11-01-custom-data-structures.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/834)

add custom structs quiz

---

po/ko.po

add Korean translate file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/839)

add Korean

---

.github/workflows/mdbook.yml

This PR fixes an issue where attempting to change the language from English to any other triggers a "Document not found (404)" error [#763](https://github.com/cairo-book/cairo-book/issues/763)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/840)

Language change issue 

---

src/SUMMARY.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/845)

chore: remove gas optimisation chapter

---

.tool-versions
listings/ch03-common-collections/no_listing_15_dict_of_array_attempt_get/output.txt
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/Scarb.toml
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/847)

chore: bump deps

---

src/ch02-02-data-types.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/859)

Move quiz to the end of the chapter in ch02-02-data-types.md

---

src/ch13-02-anatomy-of-a-simple-contract.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/860)

fix: remove redundant 'a'

---

.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/867)

ci: update release flow

---

listings/ch06-enums-and-pattern-matching/no_listing_03_enum_message/src/lib.cairo
src/ch06-01-enums.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/868)

Update enum trait section to have runnable code

---

.trunk/trunk.yaml
Cargo.lock
cairo-listings/Cargo.toml
cairo-listings/src/logger.rs
cairo-listings/src/main.rs

use multiple threads to speed up verification process
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/874)

feat(cairo-listings): parallelize verification

---

cairo-listings/src/cmd.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/875)

feat(cairo-listings): support multiple scarb versions

---

.github/workflows/ci.yml
.github/workflows/mdbook.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/878)

ci: use asdf to manage multiple scarb versions

---

src/ch14-01-contract-storage.md

Closes #877
Updates explanation for chapter 14-01 in accordance to version 2.7.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/880)

docs: Update ch14-01-contract-storage.md

---

listings/ch02-common-programming-concepts/no_listing_20_statements_dont_return_values/output.txt
listings/ch02-common-programming-concepts/no_listing_45_iter_loop_while/Scarb.toml
listings/ch02-common-programming-concepts/no_listing_45_iter_loop_while/output.txt
listings/ch02-common-programming-concepts/no_listing_45_iter_loop_while/src/lib.cairo
listings/ch02-common-programming-concepts/no_listing_46_iter_loop_for/Scarb.toml
listings/ch02-common-programming-concepts/no_listing_46_iter_loop_for/src/lib.cairo
listings/ch03-common-collections/no_listing_15_dict_of_array_attempt_get/output.txt
listings/ch04-understanding-ownership/no_listing_02_pass_array_by_value/output.txt
listings/ch04-understanding-ownership/no_listing_06_no_destruct_compile_fails/output.txt
listings/ch10-testing-cairo-programs/listing_10_01/output.txt
listings/ch10-testing-cairo-programs/no_listing_09_integration_test/output.txt
listings/ch10-testing-cairo-programs/no_listing_12_submodules/output.txt
listings/ch11-advanced-features/no_listing_06_format_macro/output.txt
listings/ch13-introduction-to-starknet-smart-contracts/listing_02_wrong_impl/output.txt
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/output.txt
src/ch02-05-control-flow.md

Closes #895
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/894)

add for-loop section in ch02-05

---

cairo-listings/src/cmd.rs
cairo-listings/src/config.rs
cairo-listings/src/main.rs

closes: https://github.com/cairo-book/cairo-book/issues/887
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/889)

feat: cairo-listings add `format` sub-command

---

src/appendix-08-system-calls.md

Fixes #723 
Please let me know if there are any revisions to be made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/902)

feat: Add Syscall for sha256 in Syscall Appendix

---

.tool-versions
listings/ch16-building-advanced-starknet-smart-contracts/listing_06_dice_game_vrf/Scarb.toml
listings/ch16-building-advanced-starknet-smart-contracts/listing_07_oz_upgrade/Scarb.toml
listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/Scarb.toml
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/.tool-versions
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/Scarb.toml
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/pizza.cairo
listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo

Closes #864
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/904)

dev: update starknet-foundry section to 2.7.0

---

theme/index.hbs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/913)

dev: add gtm

---

listings/ch14-building-starknet-smart-contracts/listing_01_reference_contract/src/lib.cairo
src/ch14-01-contract-storage.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/916)

feat: storage nodes

---

src/ch16-02-00-composability-and-components.md

Resolves : #917 
Updates the hyperlink dispatcher in : https://book.cairo-lang.org/ch16-02-00-composability-and-components.html#creating-components
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/918)

bug : ch16.2.2 dispatcher hyperlink invalid url

---

listings/ch16-building-advanced-starknet-smart-contracts/listing_04_test_component/src/tests_deployed.cairo

Resolves : #925
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/926)

bug: listing_04_test_component fails to compile

---

cairo-listings/src/config.rs
cairo-listings/src/main.rs
cairo-listings/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/927)

feat(cairo-listings): detect test modules for verification

---

.tool-versions

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/939)

remove 2.6.4 from .tool-versions

---

.tool-versions
listings/ch16-building-advanced-starknet-smart-contracts/listing_06_dice_game_vrf/Scarb.toml
listings/ch16-building-advanced-starknet-smart-contracts/listing_06_dice_game_vrf/src/lib.cairo
listings/ch16-building-advanced-starknet-smart-contracts/listing_07_oz_upgrade/Scarb.toml
listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/Scarb.toml
listings/ch16-building-advanced-starknet-smart-contracts/listing_08_price_feed/src/lib.cairo
src/ch01-01-installation.md
src/ch13-00-introduction-to-starknet-smart-contracts.md
src/title-page.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/943)

chore: bump to cairo 2.8.0

---

listings/ch02-common-programming-concepts/no_listing_47_for_range/Scarb.toml
listings/ch02-common-programming-concepts/no_listing_47_for_range/src/lib.cairo
src/ch02-05-control-flow.md

Closes #941
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/945)

feat: range operator for loops

---

README.md
docs/CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/946)

docs: contribution guide

---

src/ch01-01-installation.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/949)

chore: bump SCARB ONLY to 2.8.1

---

src/ch04-01-what-is-ownership.md

Fixes #923 
Please let me know if any further revision is needed!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/938)

docs: Rework copy trait explanation

---

listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_02_paths/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_03_pub_keyword/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_04_pub_compiles/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_06_use/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_07_use_and_scope/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_08_unidiomatic_use/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_12_pub_use/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/listing_13_front_extraction/src/lib.cairo
listings/ch07-managing-cairo-projects-with-packages-crates-and-modules/no_listing_01_lib/src/lib.cairo
src/ch07-01-packages-and-crates.md
src/ch07-02-defining-modules-to-control-scope.md
src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
src/ch07-05-separating-modules-into-different-files.md

Ready for review.
each PR is made for each sub section from 7.1 to 7.5. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/952)
Closes #942

feat: add example and explanation using crate keyword

---

src/ch14-01-00-contract-storage.md
theme/book.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/962)

fix: restore runnable code

---

quizzes/ch02-05-control-flow.toml

Sorry for the delay, I had trouble launching mdbook
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/960)

feat: add new quiz / update quiz in control flow section

---

listings/ch11-advanced-features/listing_recursive_types/Scarb.toml
listings/ch11-advanced-features/listing_recursive_types/src/display.cairo
listings/ch11-advanced-features/listing_recursive_types/src/lib.cairo
listings/ch11-advanced-features/listing_recursive_types_wrong/Scarb.toml
listings/ch11-advanced-features/listing_recursive_types_wrong/output.txt
listings/ch11-advanced-features/listing_recursive_types_wrong/src/lib.cairo
src/ch11-02-smart-pointers.md

Closes #774
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/964)

feat: recursive types

---

src/ch02-02-data-types.md

Fixes #957 
Please let me know if further revision is needed!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/959)

feat: rework byte array description

---

src/ch01-00-getting-started.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/972)

fix: changing chatbot links

---

src/ch11-06-inlining-in-cairo.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/974)

chore: nit in inlining chapter

---

src/ch16-05-01-price-feeds.md
src/ch16-05-02-randomness.md

Ready for review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/970)

refact: page layouts in the Oracle section

---

listings/ch14-building-starknet-smart-contracts/listing_01_reference_contract/src/lib.cairo
listings/ch14-building-starknet-smart-contracts/listing_simple_storage/src/lib.cairo
src/ch14-01-00-contract-storage.md

Closes #990 
@glihm sounds like the most concise way of conveying this info, wdyt?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/991)

feat: add default variant to storage enum

---

src/appendix-05-common-error-messages.md
src/appendix-06-useful-development-tools.md

Closes https://github.com/cairo-book/cairo-book/issues/993#issuecomment-2391187851
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/994)

Mention that formatting can be skipped per line using `#[cairofmt::skip]`

---

listings/ch08-generic-types-and-traits/no_listing_18_negative_impl/src/lib.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/999)

Fix Typo in Chapter 8 Code Example

---

mdbook-cairo/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1003)

refactor: mdbook cairo pre-processor

---

cairo-listings/src/main.rs
cairo-listings/src/output.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1008)

feat(cairo-listings): parallelize output processing

---

listings/ch04-understanding-ownership/no_listing_02_pass_array_by_value/src/lib.cairo
src/ch10-01-how-to-write-tests.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1011)

chore : useless `mut` + wrong failure message

---

src/ch16-04-L1-L2-messaging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1012)

Fix wording & grammar in L1-L2-messaging

---

src/ch16-03-upgradeability.md

resolves #1018
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1019)

fix: add link in upgradeable contract

---

book.toml
theme/chat.js
theme/css/chat.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/928)

feat: add ai-powered chatbot widget for efficient search

---

theme/css/chat.css
theme/css/variables.css

closes #1023 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1024)

feat: Implement theme variable support for AI-Powered Chat interface

---

theme/css/chat.css

Close #1021
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1025)

feat: fix chat positioning in bottom-right corner

---

theme/chat.js
theme/css/chat.css

Close #1022
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1026)

feat: Visual Feedback and Loading States for AI-Powered Chat

---

src/title-page.md

Closes #1016
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1036)

chore: add link to report issues in title page

---

listings/ch06-enums-and-pattern-matching/no_listing_10_match_catch_all/src/lib.cairo
listings/ch06-enums-and-pattern-matching/no_listing_11_match_or/src/lib.cairo
listings/ch06-enums-and-pattern-matching/no_listing_12_match_tuple/src/lib.cairo
listings/ch09-error-handling/listing_09_01/src/lib.cairo
listings/ch09-error-handling/listing_09_02/src/lib.cairo
listings/ch10-testing-cairo-programs/listing_10_01/src/lib.cairo
listings/ch10-testing-cairo-programs/listing_10_03/src/lib.cairo
listings/ch10-testing-cairo-programs/listing_10_04/src/add_two.cairo
listings/ch10-testing-cairo-programs/listing_10_05/src/lib.cairo
listings/ch10-testing-cairo-programs/listing_10_06/src/lib.cairo
listings/ch10-testing-cairo-programs/no_listing_02_custom_messages/src/lib.cairo
listings/ch10-testing-cairo-programs/no_listing_04_new_bug/src/lib.cairo
listings/ch10-testing-cairo-programs/no_listing_05_ignore_tests/src/lib.cairo
listings/ch10-testing-cairo-programs/no_listing_06_test_gas/src/lib.cairo
listings/ch10-testing-cairo-programs/no_listing_09_integration_test/src/lib.cairo
listings/ch10-testing-cairo-programs/no_listing_11_test_private_function/src/lib.cairo
listings/ch11-advanced-features/no_listing_15_macro/Cargo.lock
listings/ch11-advanced-features/no_listing_15_macro/Cargo.toml
listings/ch11-advanced-features/no_listing_15_macro/Scarb.toml
listings/ch11-advanced-features/no_listing_16_procedural_macro/src/lib.cairo
listings/ch16-building-advanced-starknet-smart-contracts/listing_01_storage_packing/src/lib.cairo
src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
src/ch10-01-how-to-write-tests.md

Closes #1035
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1034)

feat: glob operator

---

theme/pkg/README.md
theme/pkg/package.json
theme/pkg/wasm-cairo.d.ts
theme/pkg/wasm-cairo.js
theme/pkg/wasm-cairo_bg.wasm.d.ts

This version of WASM-Cairo support Cairo v2.8.2.
@enitrat Can you review this? Thanks!

Update WASM-Cairo to v0.10.2.

---

src/ch00-00-introduction.md
src/ch00-01-foreword.md

rework intro chapters

---

src/appendix-08-system-calls.md

feat: `get_class_hash_at_syscall`

---

src/appendix-08-system-calls.md

Doesn't close #1013  as i remember you wanted to add examples in the Hashes chapter

feat: `keccak_syscall`

---

src/SUMMARY.md
src/ch204-02-08-mod-builtin.md

feat: mod builtin

---

src/SUMMARY.md
src/ch204-02-04-bitwise.md

feat: bitwise builtin

---

src/SUMMARY.md
src/ch204-02-00-output.md

feat: output builtin

---

src/ch04-02-references-and-snapshots.md

feat: enhance snap/ref mechanism

---

src/ch01-01-installation.md

fix: starkup link

---

listings/ch101-building-starknet-smart-contracts/listing_storage_vecs/src/lib.cairo
src/ch101-01-02-storage-vecs.md

feat: update storage vec api

---

listings/ch02-common-programming-concepts/no_listing_00_consts/src/lib.cairo
src/appendix-02-operators-and-symbols.md
src/ch02-01-variables-and-mutability.md
src/ch12-05-macros.md
summary.md

refactor: deprecate consteval_int

---

src/ch101-03-contract-events.md

Added a note about using SDKs to consume events on https://book.cairo-lang.org/ch101-03-contract-events.html

Consuming events note

---

listings/ch100-introduction-to-smart-contracts/listing_01_simple_contract/Scarb.toml
listings/ch100-introduction-to-smart-contracts/listing_01_simple_contract/src/lib.cairo
listings/ch100-introduction-to-smart-contracts/listing_01_simple_contract/src/tests.cairo
listings/ch101-building-starknet-smart-contracts/listing_01_reference_contract/Scarb.toml
listings/ch101-building-starknet-smart-contracts/listing_01_reference_contract/src/lib.cairo
listings/ch101-building-starknet-smart-contracts/listing_01_reference_contract/src/tests.cairo
listings/ch101-building-starknet-smart-contracts/listing_02_storage_mapping/Scarb.toml
listings/ch101-building-starknet-smart-contracts/listing_02_storage_mapping/src/lib.cairo
listings/ch101-building-starknet-smart-contracts/listing_02_storage_mapping/src/tests.cairo
listings/ch101-building-starknet-smart-contracts/listing_events_example/Scarb.toml
listings/ch101-building-starknet-smart-contracts/listing_events_example/src/lib.cairo
listings/ch101-building-starknet-smart-contracts/listing_events_example/src/tests.cairo
listings/ch101-building-starknet-smart-contracts/listing_simple_storage/Scarb.toml
listings/ch101-building-starknet-smart-contracts/listing_simple_storage/src/lib.cairo
listings/ch101-building-starknet-smart-contracts/listing_simple_storage/src/tests.cairo

- Added comprehensive test coverage for smart contract examples using Starknet Foundry
- Added ANCHOR tags to properly isolate contracts in documentation
- Fixed missing ABI attributes where necessary
- ✅ Added ANCHOR tags to isolate contracts for documentation purposes
- ✅ Created comprehensive test suites for 5 key smart contracts:
- SimpleStorage (ch100)
- NameRegistry (ch101)
- UserValues (ch101)
- EventExample (ch101)
- SimpleStorage with enums (ch101)
- ✅ Updated Scarb.toml files with necessary test dependencies
- ✅ Fixed missing `#[abi(embed_v0)]` attribute in UserValues contract
- ✅ All tests pass successfully
This addresses issue #1187 which requested adding tests for smart contracts used as examples to prevent behavioral issues reported in #1185. By adding comprehensive test …

feat: add comprehensive tests for smart contract examples

---

listings/ch01-getting-started/prime_prover/src/lib.cairo
listings/ch01-getting-started/prime_prover2/src/lib.cairo
listings/ch06-enums-and-pattern-matching/no_listing_04_enum_option/src/lib.cairo
listings/ch08-generic-types-and-traits/listing_08_01_extracting_function_01/src/lib.cairo
listings/ch08-generic-types-and-traits/listing_08_01_extracting_function_02/src/lib.cairo
listings/ch08-generic-types-and-traits/listing_08_01_extracting_function_03/src/lib.cairo
listings/ch08-generic-types-and-traits/no_listing_05_with_anonymous_impl/src/lib.cairo
listings/ch12-advanced-features/listing_12_associated_impls/src/lib.cairo
listings/ch12-advanced-features/listing_recursive_types/src/display.cairo
listings/ch12-advanced-features/no_listing_04_hash_pedersen/src/lib.cairo

dev: refactor loops with early returns
