- src/SUMMARY.md
- src/ch01-02-hello-world.md
- src/ch02-01-variables-and-mutability.md
- src/ch02-02-data-types.md
- src/ch07-00-generic-types.md
- u256 division is now supported as per the release notes of [v1.0.0-alpha.7](https://github.com/starkware-libs/cairo/releases/tag/v1.0.0-alpha.7)
- Fixed some broken links
> Small fixes

- src/ch06-01-packages-and-crates.md
In the example of how to create a package with Scarb it is confusing that the name of the package is `my_crate` instead of `my_package`
> Fix: Changed package name in Scarb example

- src/ch02-02-data-types.md
As example code show that felt252 is smaller than a u256, we can use the into() method, which felt252 is source type and u256 is destination type.
But above descriptionis exactly opposite.
> Fix Type casting error description

- .gitignore
- README.md
- po/fr.po
Add the title-page and ch00-01-foreword translation in french.
Fix a typo in the README and add temporary files generated by editors into `.gitignore`.
> i18n: title-page and ch00-01-foreword [fr]

- README.md
Adds instructions to install `mdbook-cairo`
> Readme step: Install mdbook-cairo

- .all-contributorsrc
- README.md
- po/fr.po
Inspired by https://github.com/all-contributors/all-contributors/issues/361#issuecomment-637166066 and find that we should add a span between HTML and MD tags.
I also add a  `badgeTemplate` ( `"[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)"` ). I don't know why the original one has an extra `-` behind the `#contributors` tag.
**Before:**
**After:**
https://allcontributors.org/docs/en/bot/configuration
> Fix: "all contributors" badge does not shown.

- listings/ch04-using-structs-to-structure-related-data/listing_04_03_mut_struct.cairo
In the current version, both `Listing 4-4` and `Listing 4-5` have identical content. The latter, however, is expected to demonstrate the use of field init shorthand, which is not currently the case.
The current `Listing 4-5` is as follows:
```cairo
fn build_user_short(email: felt252, username: felt252) -> User {
User { active: true, username: username, email: email, sign_in_count: 1,  }
}
```
To correctly exemplify field init shorthand, I suggest the following revision for `Listing 4-5`:
```cairo
fn build_user_short(email: felt252, username: felt252) -> User {
User { active: true, username, email, sign_in_count: 1,  }
}
```
> Fixed field init shorthand

- listings/ch99-starknet-smart-contracts/listing_99_05_dispatcher_trait.cairo
- listings/ch99-starknet-smart-contracts/listing_99_07_library_dispatcher.cairo
Currently, the documentation indicates that the `IERC20Dispatcher` struct implements a method called `get_name` (`Listing 99-2`), while `Listing 99-3` suggests that a method called `name` should be implemented instead. The same discrepancy is observed in `LibraryDispatcher` (`Listing 99-4`).
Furthermore, it's expected that the dispatcher structs instances can be used multiple times, indicating that the implemented methods should not take ownership. However, `Listing 99-2`and `Listing 99-4` suggests that these methods take ownership, which would prohibit their multiple uses. To address this, I propose that the methods should be revised to receive a snapshot as a parameter, thereby not taking ownership.
> Fixed dispatcher naming and ownership

- listings/ch15-dictionaries/listing_15_03_custom_methods.cairo
- src/ch15-00-dictionaries.md
This PR fixes:
* small typos here and there
* updates a part of the writing to match the updates in #280 
* some coherence issues
* add some sentences and rephrase some others to make the content clearer
> Typos and coherence fixes for Dictionary Chapter

- po/es.po
- po/messages.pot
- po/zh-cn.po
- src/ch01-03-hello-scarb.md
This PR fixes a broken link for the scarb installation process
> Broken scarb installation link fix

- listings/ch99-starknet-smart-contracts/listing_99_06_sample_contract.cairo
- listings/ch99-starknet-smart-contracts/listing_99_08_using_library_dispatcher.cairo
- src/ch99-02-02-contract-dispatcher-library-dispatcher-and-system-calls.md
This PR suggests some readability improvements on top of consistent and standard-conforming contract naming.
> Improvements to the Contract Dispatchers section

- src/ch03-02-references-and-snapshots.md
> fix: explicitly state that desnap copies a value

- listings/ch99-starknet-smart-contracts/listing_99_12_vote_contract.cairo
- src/SUMMARY.md
- src/ch99-00-starknet-smart-contracts.md
- src/ch99-01-04-00-other-examples.md
- src/ch99-01-04-01-voting-contract.md
This PR initiates the migration of Cairo-related content from the Starknet Book to the Cairo Book. Specifically, Chapter 12 of the Cairo Book has been updated with selected content from the Starknet Book. This change aims to consolidate all Cairo-related material within the Cairo Book.
I propose the addition of a new section titled "Other Examples." This section will serve as a platform for the community to contribute intermediate to advanced examples of smart contracts. As a part of this initiative, I have included a Voting contract that has proven valuable in teaching Cairo for Starknet to budding developers. This curated section is intended to assist developers in learning through practical examples.
We also show how to deploy the contract and interact with it using a local node with …
> feat: Transitioning Cairo Content to Cairo Book and Introducing Intermediate to Advanced Smart Contract Examples

- listings/ch02-common-programming-concepts/no_listing_05_mut_cant_change_type/src/lib.cairo
- src/ch02-01-variables-and-mutability.md
The example given to demonstrate that a mut variable cannot change type no
longer produces the error expected from the compiler since the compiler's
type inference has improved in later versions. Instead of `.into` attempting to
convert `x` into a `felt252` it infers that the minimal required change is to
do nothing and preserve the source type. To fix this we force the issue in the
example by specifying a literal of a fixed type.
> Fix invalid mut type conversion example

- listings/ch99-starknet-smart-contracts/listing_99_03_example_contract/src/lib.cairo
Name Registry contract external function `store_name` should call internal function `_store_name`.
> Fix Name Registry contract

- listings/ch10-advanced-features/no_listing_02_array_macro/src/lib.cairo
- src/ch10-02-macros.md
This is how the `array!` code snippet currently looks like:
This is how it looks like with the fix:
> Fixed code snippets in `array!` macro chapter

- listings/ch02-common-programming-concepts/no_listing_19_blocks_are_expressions/src/lib.cairo
- listings/ch03-understanding-ownership/no_listing_09_snapshots/src/lib.cairo
- listings/ch04-using-structs-to-structure-related-data/listing_04_06_no_struct/src/lib.cairo
- listings/ch04-using-structs-to-structure-related-data/listing_04_10_print_rectangle/src/lib.cairo
- listings/ch05-enums-and-pattern-matching/listing_05_05/src/lib.cairo
- listings/ch07-generic-types-and-traits/no_listing_12_not_compiling/src/lib.cairo
- listings/ch10-advanced-features/no_listing_02_array_macro/src/lib.cairo
- src/ch02-03-functions.md
- src/ch02-99-01-arrays.md
- src/ch03-01-what-is-ownership.md
- src/ch03-02-references-and-snapshots.md
- src/ch04-02-an-example-program-using-structs.md
- src/ch05-02-the-match-control-flow-construct.md
- src/ch07-01-generic-data-types.md
- src/ch10-02-macros.md
Closes #359 
A bunch of modifications for the book to reflect the correct source code lines in the `.cairo` files after the v2 refactor
> fix: code snippets lines

- src/ch08-01-generic-data-types.md
typo fixed: `deduct` -> `deduce`
> fix: typo fixed

- listings/ch99-starknet-smart-contracts/listing_99_05_dispatcher_trait/src/lib.cairo
`ContractAddress` already brought scope from starknet crate and other places in contract as well simply used as `ContractAddress`
> Dispatcher example code sanity changes

- theme/pkg/README.md
- theme/pkg/package.json
- theme/pkg/wasm-cairo.js
As title. 
BTW, from Cairo 2.10, it has changed _print_ hint to this format(Print hex value, and no ` )` anymore. )
```
[DEBUG]	                              	(raw: 0x5
[DEBUG]	                              	(raw: 0x6
Run completed successfully, returning []
```
So maybe we need to change some content in the book for this new print format.
You can find more about WASM-Cairo 0.4.0 [here](https://github.com/cryptonerdcn/wasm-cairo/releases/tag/v0.4.0).
> Update WASM-Cairo to v0.4.0 to support Cairo v2.2.0

- listings/ch99-starknet-smart-contracts/listing_99_05_dispatcher_trait/src/lib.cairo
- listings/ch99-starknet-smart-contracts/listing_99_12_vote_contract/src/lib.cairo
Private method `_get_voting_result_in_percentage` doesn't check if `total_votes`  is `0` due to which `get_vote_status` contract call fails if we call this before any voting.
check if `total_votes` is 0 in `_get_voting_result_in_percentage` private method.
other changes: use expression syntax for returning values from method(as other methods do the same).
> Fix Vote contract example

- listings/ch05-using-structs-to-structure-related-data/listing_04_15_can_hold/src/lib.cairo
Corrected the logical operator in the `can_hold` function of the Rectangle struct to use logical AND (`&&`) instead of bitwise AND (`&`). This ensures the correct comparison of width and height between rectangles.
This change addresses a potential bug where the previous use of the bitwise AND operator led to incorrect results when comparing rectangle sizes. The fix improves the reliability of the can_hold function, particularly in scenarios where rectangles have similar widths or heights.
> Refactor can_hold function in Rectangle struct 

- src/ch99-04-00-L1-L2-messaging.md
After introduce the typo-check workflow in CI
Thanks to [PR](https://github.com/cairo-book/cairo-book/pull/445)
I found this only one typo error.
> Fix typo in src/ch99-04-00-L1-L2-messaging.md

- src/ch99-01-03-01-contract-storage.md
Hi, 
Looks like the link was broken. 
I didn't regenerate the corresponding translation files (don't know if I should).
> Link to starknet documentation storage variables was broken

- theme/index.hbs
- theme/js/index.mjs
I'm sorry for forgetting this for a long time. 
Basically before this PR, you can only run the code in the English version of CairoBook -- Because the js files are just under the `root/js`, so it can't be used in the subpath(such as `root/zh-cn/`).
Now all language versions of Cairobook can run the code!
You can test it here: 
https://starknetastro.github.io/cairo-book.github.io/zh-cn/ch01-02-hello-world.html
BTW: Because of Webworker's relative path problem I had to use an ugly way to solve this. https://github.com/parcel-bundler/parcel/issues/5430. I will update it when I find a good way.
@enitrat Can you review this PR? Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [feat]Let wasm-cairo run in each languages' path.

- src/ch02-05-control-flow.md
In the commit https://github.com/cairo-book/cairo-book/pull/472/commits/d91cbff8916f0931aeff9e693c9ef40cfb97aeec `'again!'.print();` has been reworked to `println!("i = {}", i);` to use the new `println!` macro.
So now, the code snippet in the loop chapter should be updated as `i = 0` is printed instead of `again!`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/485)
> Small update in 'control flow' chapter

- listings/ch08-generic-types-and-traits/no_listing_02_with_tdrop/src/lib.cairo
- listings/ch08-generic-types-and-traits/no_listing_03_missing_tcopy/src/lib.cairo
In the chapter 8.1 "Generic Functions", anonymous generic implementation parameters are described at the end of the chapter (in "Anonymous Generic Implementation Parameter (+ operator)" but they are used in the second and third code snippets, at the beginning of the chapter.
Then, the chapter "Constraints for Generic Types" mentions a `TDrop` implementation but in the code snippet, the drop implementation is anonymous.
To be more consistent with the chapter structure, this PR uses named generic implementation parameters in the first code snippets, until anonymous generic implementation parameter are described.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/489)
> Anonymous vs Named Generic Implementation Parameter

- listings/ch08-generic-types-and-traits/no_listing_14_compiling/src/lib.cairo
At the end of the chapter 8.1, 2 `Wallet` are instanciated with the following code:
```
let w1 = Wallet { balance: true, address: 10 };
let w2 = Wallet { balance: 32, address: 100 };
```
Then, a paragraph explains that we create 2 instances: one of `Wallet<bool, u128>` and the other of `Wallet<felt252, u8>`.
I think that it's not correct as the compiler will use `felt252` to store `10`, `32` and `100` values by default.
To be sure to have an instance of `Wallet<bool, u128>` and another of `Wallet<felt252, u8>`, we have to use `10_u128` and `100_u8`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/490)
> Issue in wallet field types

- src/ch07-02-defining-modules-to-control-scope.md
Replacing :
The line `use garden::vegetables::Asparagus;` lets us **use** bring the `Asparagus` type into scope,
so we can use it in the `main` function.
with :
The line `use garden::vegetables::Asparagus;` lets us bring the `Asparagus` type into scope,
so we can use it in the `main` function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/492)
> Fix small typo in 7.2. defining modules

- po/messages.pot
- po/zh-cn.po
- src/ch11-03-hash.md
- Making this amazing resource more typo free.
Replaced term `updateted` with `updated`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/486)
> Minor Typo fix in Chapter 10.3

- listings/ch99-starknet-smart-contracts/listing_99_03_example_contract/src/lib.cairo
- src/ch99-01-03-02-contract-functions.md
- src/ch99-01-03-04-reducing-boilerplate.md
By reading the explanation about how to write internal functions in a Cairo smart contract, it's not clear if these internal functions must be in an implementation block to access to `ContractState` or not, as the free function `get_owner_storage_address` uses the ContractState and is not in an implementation block.
After discussion on the Starknet discord, it appears that internal functions just have to be outside the implementation block tagged with `#[abi(embed_v0)]`. That means, they can be grouped in an implementation block if it makes the code more readable/easier to use, or just be added as free functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/509) …
> Internal functions in a smart contract

- src/ch03-02-dictionaries.md
- src/ch04-01-what-is-ownership.md
- src/ch04-02-references-and-snapshots.md
- src/ch09-01-how-to-write-tests.md
- src/ch99-01-01-introduction-to-smart-contracts.md
Noticed some mistakes when reading the book, this PR makes minor changes to fix them:
* "the a variable" -> "a variable"
* "two tests functions" -> "two test functions"
* "passing as snapshot" -> "passing as a snapshot"
* a few missing commas
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/522)
> proofread and fix a few grammar mistakes

- src/ch99-04-00-L1-L2-messaging.md
@enitrat I was wrong about messaging on the wording. We had a fix on Katana and Devnet which corrected how messaging fields were extracted from blockifier.
This PR aims at giving a more accurate information to the reader.
Also from some feedback, users are trying to directly call the starknet core contract. I added some rewording to avoid this too.
Sorry again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/521)
> fix: adjust messaging content after feedbacks from users

- listings/ch02-common-programming-concepts/no_listing_10_short_string_type/src/lib.cairo
- src/ch02-02-data-types.md
Related to https://github.com/cairo-book/cairo-book/issues/585.
I've started rewriting the 'string types' section in the 'Data types' chapter. 
In the issue, you talk about a dedicated page for `ByteArray`. So, for 'ByteArray' strings, I don't know if I have to explain more things or if we will just pointing to this dedicated page for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/593)
> chore: 'rework string types' section in the 'Data types' chapter

- mdbook-cairo/src/lib.rs
This PR allows detection of empty lines after TAG, in order to remove them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/594)
> feat: update mdbook preprocessing

- src/ch05-03-method-syntax.md
- src/ch06-01-enums.md
- src/ch06-02-the-match-control-flow-construct.md
- src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
- src/ch07-05-separating-modules-into-different-files.md
- src/ch08-00-generic-types-and-traits.md
Added some links to the mentioned concepts + some minor stylistic fixes.
Two things I'm not sure about:
[Here](https://book.cairo-lang.org/ch07-02-defining-modules-to-control-scope.html#grouping-related-code-in-modules) it states that code within modules is private by default but [here](https://book.cairo-lang.org/ch07-05-separating-modules-into-different-files.html#summary) it's public by default. I corrected it to private, but please have a closer look. 
[Here](https://book.cairo-lang.org/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html#using-external-packages-in-cairo-with-scarb) git branch imports are mentioned as deprecated but I couldn't find a reference to it in the current [Scarb docs](https://docs.swmansion.com/scarb/docs/guides/dependencies.html). I can fix it if it's …
> add references + stylistics

- listings/ch04-understanding-ownership/listing_04_05/src/lib.cairo
- listings/ch04-understanding-ownership/no_listing_10_desnap/src/lib.cairo
excess Copy
```rust
#[derive(Copy, Drop)]
struct Rectangle {
height: u64,
width: u64,
}
fn main() {
let rec = Rectangle { height: 3, width: 10 };
let area = calculate_area(rec);
println!("Area: {}", area);
}
fn calculate_area(rec: Rectangle) -> u64 {
rec.height * rec.width
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/667)
> feat: delete Copy trait in snapshots

- .github/workflows/install-mdbook/action.yml
- .gitignore
- book.toml
- quizzes/ch01-01-installation.toml
- quizzes/ch01-02-hello-world.toml
- quizzes/ch02-01-variables-and-mutability.toml
- src/ch01-01-installation.md
- src/ch01-02-hello-world.md
- src/ch02-01-variables-and-mutability.md
#658 
- Add `mdbook-quiz` preprocessor
- Add sample questions for each available question type
@enitrat Please have a look if you want some setting from [here](https://github.com/cognitive-engineering-lab/mdbook-quiz?tab=readme-ov-file#quiz-configuration) to be added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/660)
> add initial mdbook-quiz config with sample questions

- src/ch14-02-contract-functions.md
Technically there is no view function in Starknet that ensures no state change happens during an external call. Calling a view function in an untrusted contract does not prevent the callee from reentering the main contract and triggering functions that change the state.
Hence I rephrased the public function description and fully removed the view function description to avoid any misunderstanding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/686)
> Fix public function description

- cairo-documentation-style-guide.md
Closes #717 
Style guide for contributions. 
The style guide was adapted from https://github.com/esp-rs/book/blob/main/rust-doc-style-guide.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/720)
> cairo-documentation-style-guide issue # 717

- src/ch11-06-macros.md
#737 Dead Link on Macro
Fixed the dead link on Macro for the entry point selector item, works as shown below
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/739)
> Fixed Issue #737

- quizzes/ch03-01-arrays.toml
- src/ch03-01-arrays.md
Requires a fork of mdbook-quiz to validate using scarb rather than rustc.
Depends on https://github.com/cairo-book/cairo-book/issues/745
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/744)
> feat: quiz arrays

- listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/Scarb.toml
- listings/ch17-starknet-smart-contracts-security/listing_02_pizza_factory_snfoundry/src/tests/foundry_test.cairo
- src/ch17-02-testing-smart-contracts.md
[Starknet Foundry](https://github.com/foundry-rs/starknet-foundry) changed its syntax to impersonate addresses in tests. They abandoned the Foundry-style naming (`prank`/`warp`/etc..) for more explicit naming (`cheat_caller_adress`/`cheat_block_timestamp`/`cheat_block_number`, etc.._)
See the latest [Starknet Foundry release](https://github.com/foundry-rs/starknet-foundry/releases/tag/v0.24.0) for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/810)
> refactor: update impersonation syntax

- src/SUMMARY.md
- src/ch200-introduction.md
Closes #757 
All the chapters are currently empty except for the introduction with an empty file (enforcing the convention `ch20x-chapter.md`.
Should the writing of the introduction be in this PR or in a separated one?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/848)
> feat: add Cairo VM sub-book skeleton

- listings/ch02-common-programming-concepts/no_listing_32_infinite_loop/src/lib.cairo
- src/ch02-05-control-flow.md
This is not real information, currently 'break' isn't needed for compilation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/856)
> docs: ch02-05-control-flow.md

- src/ch14-01-contract-storage.md
Closes #930 
for expanding to work, we need `#rustdoc_include` instead of `#include`
here I updated only the one that was mentioned, but `#include` is used in many many other files, but its not always necessary to allow expanding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/940)
> fix(docs): use `#rustdoc_include` to allow expanding for `Map` example

- book.toml
- src/ch14-01-00-contract-storage.md
- theme/book.js
Fixes #961
`#` -> `# `. Fixes conflicts with derive directives.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/963)
> fix: cairo hidden lines

- listings/ch14-building-starknet-smart-contracts/listing_01_reference_contract/src/lib.cairo
- src/ch14-01-01-storage-mappings.md
- src/ch14-03-contract-events.md
@enitrat  there is a listing that doesnt point to anything at the end of Mapping Storages chapter. i dont think any listing is required here
also updated an anchor to snake case
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/955)
> chore : remove dead listing in mappings chapter

- src/ch01-02-hello-world.md
The `scarb new` command gives user two options to either use 
> `test (default)` dependency
> `Starknet Foundry` dependency
Even though these are referenced later in the tutorial , this has been missed in `creating hello world project` section.
Additionally , the `Scarb.toml` file also contains some new information that was missing in the chapter so i've added that too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/988)
> Added missing intermediate steps of `scarb new`

- .github/workflows/ci.yml
- .github/workflows/mdbook.yml
- .github/workflows/release.yml
Adds `pnpm` to CI, required for Depot installations.
Closes https://github.com/cairo-book/cairo-book/issues/1027
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cairo-book/cairo-book/1028)
> ci: add pnpm to ci

- listings/ch03-common-collections/no_listing_04_array_at/src/lib.cairo
From the at method section for getting items from an array, the variables 'first' and 'second' were assumed to have been declared as a reference was made to them but they were never declared in the code section. so I declared the first and second variables let first = *a.at(0);
let second = *a.at(1);
I followed the method of dereferencing the array before accessing the values cause that what the rest of the code section used. The same result  can be achieved without dereferencing the array  let first = a.at(0);
let second = a.at(1);
> fix: array `at` code example incoherent with explanation

- src/ch11-08-printing.md
Refer to https://github.com/cairo-book/cairo-book/issues/1031.
Note that, hexadecimal formatting will also be available with the `Debug` trait soon (see https://github.com/starkware-libs/cairo/pull/4553).
> feat: Hex formatting with {:x}

- listings/ch101-building-starknet-smart-contracts/listing_01_reference_contract/src/lib.cairo
- src/ch101-00-building-starknet-smart-contracts.md
- src/ch101-02-contract-functions.md
- Simplification of the NameRegistry contract to match the topic
- Move NameRegistry to 14.2 so that it is displayed only for its page
- Add windows to display the entire contract in the examples
> fix: code examples not matching reference contract

- quizzes/ch08-02-traits.toml
The context provides a contradictory explanation for the compilation error in the Trait quiz as it is mentioned in the chapter that default implementation is supported.
> Fix: Incorrect context

- README.md
Small fix for incorrect path to CONTRIBUTING.md in README.md
> Fix: README `./docs/CONTRIBUTING.md`

- src/ch05-03-method-syntax.md
1. Fix a little typo where a trait function was namespaced using the struct instead of the trait.
2. Fix a little grammar typo.
> fix(struct): Associated function namespaced using trait

- listings/ch103-building-advanced-starknet-smart-contracts/listing_03_component_dep/src/counter.cairo
- src/ch103-02-02-component-dependencies.md
`_transfer_ownership` doesn't check the caller address and can allow anyone to transfer ownership.
> dev: use owner-gated `transfer_ownership` in component example

- src/ch01-01-installation.md
This PR adds the missing `scarb --version` command to the [[installation guide](https://book.cairo-lang.org/ch01-01-installation.html)](https://book.cairo-lang.org/ch01-01-installation.html).  
Previously, the guide displayed the expected version output for Scarb, Cairo, and Sierra, but did not show the actual command used to generate that output.
- Added the following command just before the output block:
```bash
$ scarb --version
```
Including the command improves clarity, especially for newcomers who may not immediately know how to verify the Scarb installation.
> 📚 Add missing `scarb --version` command to installation guide

- quizzes/ch05-02-an-example-program-using-structs.toml
Fixes a typo in the Cairo Book:quiz where the term "area" was incorrectly used in a context where "perimeter" is the correct term.
This might cause confusion for readers, especially those trying to follow along with geometric or mathematical examples in the chapter.
- Replaced “area” with “perimeter” in the appropriate sentence.
- Ensured the correction maintains the original intent and readability of the paragraph.
> Fix incorrect usage of "area" instead of "perimeter"

- src/ch08-01-generic-data-types.md
This PR improves the readability of a sentence in the generics section.
- The original sentence was grammatically correct but somewhat awkward and difficult to parse.
- The updated version provides a clearer and more natural flow, making it easier for readers to understand the intent of the example.
Before:
> "Imagine that we want, given a list of elements of some generic type T, to find the smallest element among them."
After:
> "Imagine we have a list of elements of some generic type T, and we want to find the smallest element among them."
No changes to logic or content — just a style/clarity improvement.
> docs: rephrase generics example sentence for clarity
